import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/providers/app_providers.dart';
import '../../../../core/services/location_service.dart';
import '../../../../core/services/falcon_voice_assistant_service.dart';

class FalconVoiceModal extends ConsumerStatefulWidget {
  const FalconVoiceModal({super.key});

  static void show(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => const FalconVoiceModal(),
    );
  }

  @override
  ConsumerState<FalconVoiceModal> createState() => _FalconVoiceModalState();
}

class _FalconVoiceModalState extends ConsumerState<FalconVoiceModal>
    with SingleTickerProviderStateMixin {
  late AnimationController _pulseController;
  late Animation<double> _pulseAnimation;

  String _currentTranscript = 'Listening for "Hey Falcon..."';
  String _aiResponse = 'Speak your emergency command or select a quick voice trigger below.';
  bool _isProcessing = false;

  @override
  void initState() {
    super.initState();
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1000),
    )..repeat(reverse: true);

    _pulseAnimation = Tween<double>(begin: 0.9, end: 1.15).animate(
      CurvedAnimation(parent: _pulseController, curve: Curves.easeInOut),
    );
  }

  @override
  void dispose() {
    _pulseController.dispose();
    super.dispose();
  }

  Future<void> _handleCommand(String phrase) async {
    setState(() {
      _currentTranscript = '"$phrase"';
      _isProcessing = true;
      _aiResponse = 'Processing intent & triangulating emergency coordinates...';
    });

    final userCoords = ref.read(currentLocationProvider).value ?? LocationService.defaultCoordinates;
    await Future.delayed(const Duration(milliseconds: 600));

    final result = await FalconVoiceAssistantService.processVoiceCommand(phrase, userCoords);

    if (!mounted) return;

    setState(() {
      _isProcessing = false;
      _aiResponse = result.responseMessage;
    });

    // If a hazard was generated by voice, inject into global map state immediately!
    if (result.generatedHazard != null) {
      ref.read(hazardListProvider.notifier).addHazard(result.generatedHazard!);
      ref.read(mapFocusCoordinateProvider.notifier).setCoordinate(result.generatedHazard!.coordinates);
    }

    // If a target tab is specified, switch after a brief pause so user hears/sees confirmation
    if (result.targetTabIndex != null) {
      await Future.delayed(const Duration(milliseconds: 1400));
      if (!mounted) return;
      Navigator.pop(context);
      ref.read(bottomNavIndexProvider.notifier).setIndex(result.targetTabIndex!);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: result.isEmergency ? const Color(0xFFDC2626) : Colors.black87,
          content: Row(
            children: [
              Icon(result.isEmergency ? Icons.warning : Icons.check_circle, color: Colors.white, size: 18),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  result.isEmergency ? '🚨 VOICE SOS PINNED TO RADAR MAP' : 'Map updated via Falcon Voice AI',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 12),
                ),
              ),
            ],
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF0D0D0D) : Colors.white,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(24)),
        border: Border.all(color: isDark ? const Color(0xFF262626) : const Color(0xFFE5E7EB)),
        boxShadow: const [BoxShadow(color: Colors.black45, blurRadius: 20)],
      ),
      padding: const EdgeInsets.fromLTRB(20, 14, 20, 28),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Drag Handle
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: isDark ? Colors.white24 : Colors.black12,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Header
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  Container(
                    width: 32,
                    height: 32,
                    decoration: BoxDecoration(
                      color: isDark ? Colors.white : Colors.black,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Icon(
                      Icons.graphic_eq,
                      color: isDark ? Colors.black : Colors.white,
                      size: 18,
                    ),
                  ),
                  const SizedBox(width: 10),
                  const Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Falcon Voice AI',
                        style: TextStyle(fontWeight: FontWeight.w900, fontSize: 16),
                      ),
                      Text(
                        'Hands-Free Disaster Dispatch',
                        style: TextStyle(fontSize: 10, color: Colors.grey),
                      ),
                    ],
                  ),
                ],
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0xFF059669).withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Row(
                  children: [
                    Icon(Icons.fiber_manual_record, color: Color(0xFF059669), size: 10),
                    SizedBox(width: 4),
                    Text('MIC ACTIVE', style: TextStyle(color: Color(0xFF059669), fontSize: 9, fontWeight: FontWeight.bold)),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),

          // Pulsating Voice Orb
          ScaleTransition(
            scale: _pulseAnimation,
            child: Container(
              width: 84,
              height: 84,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: _isProcessing
                      ? [const Color(0xFF2563EB), const Color(0xFF1D4ED8).withValues(alpha: 0.2)]
                      : [const Color(0xFFDC2626), const Color(0xFFEF4444).withValues(alpha: 0.15)],
                ),
                boxShadow: [
                  BoxShadow(
                    color: (_isProcessing ? const Color(0xFF2563EB) : const Color(0xFFDC2626)).withValues(alpha: 0.4),
                    blurRadius: 20,
                    spreadRadius: 4,
                  ),
                ],
              ),
              child: Icon(
                _isProcessing ? Icons.auto_awesome : Icons.mic,
                size: 38,
                color: Colors.white,
              ),
            ),
          ),
          const SizedBox(height: 20),

          // User Transcript Box
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
            decoration: BoxDecoration(
              color: isDark ? const Color(0xFF1A1A1A) : const Color(0xFFF9FAFB),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: isDark ? const Color(0xFF333333) : const Color(0xFFE5E7EB)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'SPOKEN INPUT:',
                  style: TextStyle(fontSize: 9, fontWeight: FontWeight.bold, color: isDark ? Colors.white38 : Colors.black38),
                ),
                const SizedBox(height: 4),
                Text(
                  _currentTranscript,
                  style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w800, fontStyle: FontStyle.italic),
                ),
              ],
            ),
          ),
          const SizedBox(height: 12),

          // Falcon AI Speech Output
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: const Color(0xFF2563EB).withValues(alpha: 0.08),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: const Color(0xFF2563EB).withValues(alpha: 0.25)),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.shield, color: Color(0xFF2563EB), size: 18),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    _aiResponse,
                    style: const TextStyle(fontSize: 12, height: 1.4, fontWeight: FontWeight.w600),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),

          // Quick Demonstration Voice Triggers (One-Tap Voice Commands)
          const Align(
            alignment: Alignment.centerLeft,
            child: Text(
              'Voice Triggers (Tap to Speak):',
              style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold),
            ),
          ),
          const SizedBox(height: 8),
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              children: [
                _buildVoiceTriggerChip(
                  label: '🚨 "Hey Falcon, I am in danger, report the issue!"',
                  command: 'Hey Falcon, I am in danger, report the issue!',
                  isPrimary: true,
                ),
                const SizedBox(width: 8),
                _buildVoiceTriggerChip(
                  label: '🌊 "Hey Falcon, severe flood rising, report!"',
                  command: 'Hey Falcon, severe flood rising, report the issue!',
                ),
                const SizedBox(width: 8),
                _buildVoiceTriggerChip(
                  label: '⚡ "Hey Falcon, live power line on road!"',
                  command: 'Hey Falcon, live power lines on the road!',
                ),
                const SizedBox(width: 8),
                _buildVoiceTriggerChip(
                  label: '🗺️ "Hey Falcon, open live map"',
                  command: 'Hey Falcon, open live map',
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildVoiceTriggerChip({
    required String label,
    required String command,
    bool isPrimary = false,
  }) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return ActionChip(
      backgroundColor: isPrimary
          ? const Color(0xFFDC2626)
          : (isDark ? const Color(0xFF1E1E1E) : const Color(0xFFF3F4F6)),
      label: Text(
        label,
        style: TextStyle(
          color: isPrimary ? Colors.white : (isDark ? Colors.white : Colors.black),
          fontSize: 11,
          fontWeight: isPrimary ? FontWeight.w900 : FontWeight.w600,
        ),
      ),
      side: BorderSide(
        color: isPrimary ? const Color(0xFFDC2626) : (isDark ? const Color(0xFF333333) : const Color(0xFFE5E7EB)),
      ),
      onPressed: () => _handleCommand(command),
    );
  }
}
